# Generated by Django 6.0.1 on 2026-02-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('self', 'Self'), ('google', 'Google'), ('github', 'Github'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('linkedin', 'LinkedIn')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
